clock.js
main.js

This commit fixes a persistent initialization bug where the polar clock would fail to render on initial page load. The root cause was a combination of a premature resize call and a non-deterministic `setTimeout` for hiding the loading screen.
The new implementation uses a robust, event-driven approach:
1.  **`clock.js`**: The `ClockModule` now emits a custom `clockready` event after it has successfully drawn its first frame. The premature `resize()` call within `init()` has also been removed to prevent incorrect dimension calculations.
2.  **`main.js`**: The main application logic now listens for the `clockready` event. The loading overlay is only hidden *after* this event is received, guaranteeing that the clock is visible and ready. The initial `resize()` call is still triggered by a …

fix: Implement event-driven approach for initial clock render

---

index.html

This commit introduces two new features to the polar clock:
1.  A new, toggleable 'Week of the Year' data arc.
*   Adds a 'showWeekBar' setting to control visibility.
*   Includes a new toggle in the settings panel.
*   The clock's drawing and resizing logic is updated to handle the new, optional arc.
*   A new color has been added to all palettes for the week arc.
2.  Re-implements decorative separator lines for all time and date arcs.
*   A reusable `drawSeparators` function is created to draw radial lines with a 'cutout' effect by using the background color.
*   The lines are drawn conditionally based on the 'Date Lines' and 'Time Lines' settings.
*   The separator at the 6 o'clock position is skipped as requested.
*   The number of separators is dynamic (e.g., days in month, 52 for …

feat: Add 'Week of the Year' arc and separator lines

---

index.html

This commit fixes a bug in the Inverse Clock Mode feature where the arcs were emptying in a counter-clockwise direction instead of clockwise.
The drawing logic has been corrected to modify the start angle of the arc instead of the end angle, which produces the desired visual effect.
The `getDisplayProgress` function has been replaced with a more comprehensive `getArcAngles` helper function to handle the new logic.

fix: Correct Inverse Mode drawing direction

---

index.html

This feature extends the Inverse Mode functionality to the Pomodoro timer.
When the Pomodoro tool is active, the main clock face now displays the Pomodoro timer's progress using the minutes and seconds arcs.
This new visualization respects the global "Inverse Mode" setting.
The other clock arcs are hidden during a Pomodoro session, and the labels show the remaining Pomodoro time.

feat: Extend Inverse Mode to Pomodoro tool

---

index.html

Refactored the animation logic to use a single, authoritative `requestAnimationFrame` loop within the main `update(timestamp)` function.
Removed a redundant and conflicting animation loop from the `Clock` module. The `Clock` module now exposes a `draw()` method that is called on each frame by the main `update` loop.
This also removes the unnecessary `pause()` and `resume()` logic and their call sites, which were causing runtime errors.
This ensures the clock correctly displays the current time on startup and animates in real-time as intended.

Fix: Correct animation loop to make clock live

---

index.html

This commit refactors the `startNextPhase` function in the Pomodoro module to resolve a critical bug that caused the timer to fail.
The previous implementation had an ambiguous logical structure that failed to correctly reset the timer state when transitioning from a work or break cycle. This resulted in the timer getting stuck on a negative value and the end-of-cycle bell sound not playing.
The new implementation uses a clear `if/else` block to explicitly handle the state transitions:
- `if (phase === 'work')`: transitions to the appropriate break.
- `else`: transitions from a break back to a work session.
This makes the code more robust and ensures the Pomodoro timer operates reliably.

fix: Refactor Pomodoro phase transition logic

---

index.html

Implements a visual warning for the Pomodoro timer by making the timer arcs brighter during the final three minutes of a cycle.
This feature provides a non-intrusive visual cue to the user that a work or break session is nearing its end.
Key changes:
- Defines brighter color variants for the minute and second arcs in all color palettes.
- Modifies the `drawPomodoroClock` function to check the timer's state on each frame.
- If the remaining time is less than or equal to 3 minutes and the requisite settings are enabled, the arcs are drawn with their brighter colors.
- The effect is controlled by the existing "Glow Effect" and "Pulse Effect" toggles, and is disabled if either is turned off.
- The implementation is state-driven and does not mutate the arc objects, preventing rendering bugs.

feat: Add bright arc warning to Pomodoro timer

---

index.html

Implements a visual warning for the Pomodoro timer. During the last 2 minutes of any cycle, the entire clock container will now glow with a yellow warning color and pulsate simultaneously.
This feature provides a clear, unmissable visual cue that a work or break session is nearing its end.
Key changes:
- Adds a new CSS class and @keyframes animation for the yellow 'glowing-warning' effect.
- Modifies the main `update` function to add/remove both the '.glowing-warning' and existing '.pulsing-warning' classes from the clock container.
- The effect is triggered when the timer has <= 120 seconds remaining.
- This feature is controlled by the existing 'Glow Effect' and 'Pulse Effect' toggles; both must be enabled for the effect to appear.

feat: Add glow and pulse warning to Pomodoro timer

---

index.html

This commit introduces Mute and Snooze buttons for the Pomodoro timer and includes fixes for audio playback based on user feedback.
- **Mute/Snooze Buttons:** Appear during the last 60 seconds of a timer cycle.
- **Mute Action:** Silences the current audio cue and provides visual feedback by turning the button red.
- **Snooze Action:** Silences the audio, adds 5 minutes to the timer (stackable), and updates the UI to a "Snoozing" state with red timer text.
- **Audio Logic:** The correct, phase-specific sound (`work_end.mp3`, `short_break_end.mp3`, `long_break_end.mp3`) now plays from the `assets/Sounds/` directory during the last minute of the corresponding cycle.
All state, including mute status and button visibility, is correctly managed and reset for each new cycle.

feat: Implement Pomodoro Mute and Snooze buttons with audio fixes

---

index.html

This commit fixes a bug where the last-minute audio cue would not play again if the timer had been snoozed.
The `snoozePomodoro()` function is updated to reset the `lastMinuteSoundPlayed` state flag to `false`. This ensures that when the snoozed timer counts down to the 60-second mark again, the application is ready to play the audio cue as intended.
This is the final fix for the Mute/Snooze feature, which is now complete and working as per all user requirements.

fix: Allow audio cue to re-trigger after snoozing

---

index.html

This commit refactors the Pomodoro timer controls to merge the separate "Start" and "Pause" buttons into a single, stateful toggle button.
- The button's text and color now change dynamically to reflect the timer's state (Stopped, Running, Paused), providing a more intuitive user experience.
- A new `toggle()` function manages the state transitions, and the `reset()` function is updated to correctly revert the button to its initial "Start" state.

feat: Consolidate Start and Pause buttons for Pomodoro timer

---

index.html

This commit integrates the Pomodoro timer's state with the main polar clock display.
- When the Pomodoro tab is active, the clock now switches from displaying the time of day to a dedicated countdown visualization.
- A new `drawPomodoroClock()` function renders a single arc representing the timer's progress.
- The central digital display is also updated to show the remaining Pomodoro time (MM:SS) and hides the date.
- The Pomodoro state has been refactored to include `totalSeconds` to facilitate the arc progress calculation.
This change provides a much more intuitive and functional user experience, as the main clock now correctly reflects the active Pomodoro timer.

feat: Display Pomodoro countdown on main polar clock

---

index.html

This commit fixes a visual bug where the Pomodoro countdown arc on the main clock display was filling up instead of emptying.
The logic in the `drawPomodoroClock` function has been corrected to calculate the arc's start and end angles properly, ensuring the arc shrinks as the timer counts down. This aligns the visualization with the expected behavior of a countdown timer.

fix: Correct Pomodoro countdown arc drawing direction

---

index.html

This commit addresses several issues with the clock's display and the Pomodoro timer's functionality.
The main clock's minute hand calculation has been adjusted to remove the 'smoothing' effect from the seconds, making it jump from minute to minute.
The Pomodoro timer's digital display has been made more robust against floating-point inaccuracies, ensuring it shows the correct remaining time.
The visual representation of the Pomodoro timer on the clock face has been corrected to show two separate arcs for remaining minutes and seconds, behaving like countdown clock hands rather than a single progress bar for the entire session.

Fix: Correct clock display and Pomodoro timer logic

---

index.html

This commit introduces a new 'Continuous' toggle to the Pomodoro timer settings.
The 'Glow Effect' and 'Pulse Effect' toggles and their associated CSS effects and JavaScript logic have been removed to make way for the new feature.
The new 'Continuous' toggle has been added to the UI and is connected to the settings, but it does not have any functionality yet. This will be implemented in a future change.

Feat: Add Continuous toggle for Pomodoro timer

---

index.html

This commit enhances the Pomodoro timer to support longer work sessions.
- An hours input field has been added to the Pomodoro settings UI, allowing users to set work durations longer than 59 minutes.
- The JavaScript logic for calculating the Pomodoro duration has been updated to incorporate the value from the new hours field.
- The digital display for the Pomodoro timer now formats the time as HH:MM:SS when the total duration is an hour or more.
- The canvas display for the Pomodoro clock has been updated to conditionally draw an hour arc when the duration is an hour or more, with the clock face resizing to accommodate it.

Feat: Add hours input and display to Pomodoro timer

---

index.html

This commit updates the Pomodoro timer to use hosted URLs for its end-of-cycle audio cues. This ensures that the sounds are accessible to all users on all devices, as they are no longer dependent on local file paths.
- The `update` function now constructs full URLs to the raw audio files on GitHub.
- The `playSound` function has been made more robust to handle both full URLs and local file names, ensuring that other sounds in the application continue to function correctly.

Fix: Use hosted URLs for Pomodoro sounds

---

index.html

Removes the confusing and redundant toggles for "Date Lines," "Time Lines," and "Show Week Bar" from the settings panel. Replaces them with two new, non-functional button groups for "Intervals" and "Mode" as per user specification.
This change cleans up the UI and removes orphaned JavaScript to prevent console errors.

Refactor(settings): Redesign Separators UI controls

---

index.html

Removes the confusing toggles from the "Separators" settings and replaces them with two new, side-by-side button-based controls for "Intervals" and "Mode".
This change implements a cleaner, more compact layout and adds JavaScript to provide visual feedback (active state toggling) and state persistence for the new controls, addressing user feedback from the previous version.

feat(settings): Redesign Separators UI and add interactivity

---

index.html

This commit refines the "Standard" separator mode to reduce visual clutter, based on user feedback.
In "Standard" mode, the Minute and Second arcs now only display the 12 separator lines that align with the hours on a clock face (i.e., at 5-minute/second intervals).
The "Ruler" mode and the separator display for all other arcs (Hour, Day, Month) remain unchanged.

refine(settings): Reduce separator density in Standard mode

---

index.html

Replaces the "Date Lines" and "Time Lines" toggles with new "Intervals" (Show/Hide) and "Mode" (Standard/Ruler) button groups.
The "Ruler" mode adds detailed tick marks for the minute and second arcs, while other arcs retain standard separators. The visibility of all separators is now controlled by the "Intervals" buttons.
All clock arcs (Month, Day, Hour, Minute, Second) are now permanently visible, simplifying the rendering logic. The state of the new controls is persisted in localStorage.
Also removes the defunct "Show Weeks Bar" toggle.

feat: Overhaul separator controls with ruler mode

---

index.html

This commit fixes a visual bug where the Pomodoro timer mode did not show its dedicated countdown display on the main canvas.
- A new `drawPomodoro` function has been created to render the Pomodoro-specific view, as originally requested for better modularity.
- The main `animate` loop is updated to call `drawPomodoro` when the application is in pomodoro mode.
- In Pomodoro mode, the canvas now displays the standard Hours, Minutes, and Seconds arcs, with a new innermost arc representing the Pomodoro timer's progress. The date-related arcs (Month, Day, Week) are hidden.
- The Pomodoro arc's color changes based on the current phase (work/break).
- The `resize` function has been updated to correctly calculate the canvas layout for all modes, ensuring the display is …

feat: Implement Pomodoro timer display on canvas

---

js/clock.js

This commit adds the 'ruler' separator style to the Pomodoro timer view.
The `drawPomodoro` function in `js/clock.js` has been updated to check the `settings.separatorMode` and call the appropriate separator drawing function (`drawRulerSeparators` or `drawSeparators`) for the minutes and seconds arcs. This aligns its behavior with the main clock view.

Feat: Apply ruler mode to Pomodoro timer

---

js/clock.js

This commit updates the Pomodoro timer to use the colors from the currently selected color theme, instead of hardcoded colors.
The `drawPomodoro` function in `js/clock.js` has been modified to fetch colors for the hours, minutes, and seconds arcs from the `settings.currentColors` object. This makes its appearance consistent with the main clock and other themed elements.

Feat: Apply theme colors to Pomodoro timer

---

index.html
js/ui.js

The "Alarm" tab in the "Tools" view was redundant as its functionality is covered by the "Timer" tool and the more advanced alarm features are on a separate "Alarms" page.
This commit removes the "Alarm" tab button and its corresponding panel from `index.html`, and removes the associated JavaScript references and event listeners from `js/ui.js` to streamline the user interface.

Remove redundant Alarm tab from Tools view

---

index.html
js/main.js

This commit introduces a new settings modal for the Pomodoro timer, allowing users to customize the duration of the work, short break, and long break cycles.
- A new "Custom" button in the Pomodoro panel to open the settings modal.
- A new modal titled "Custom Cycles" with wider input fields for the three durations.
- "Smart" input fields that accept minutes and reformat to HH:MM:SS on blur.
- The settings are saved to `localStorage` to persist between sessions.
- The Pomodoro timer logic is updated to use the new settings.
- Closing the modal immediately applies the new settings to the timer.

feat: Implement Pomodoro settings modal with custom cycles

---

index.html
js/clock.js
js/main.js

This commit introduces several UX improvements to the Pomodoro timer based on user feedback.
- The font for the entire application has been changed to "Oswald".
- The "Custom Cycles" modal now has "Submit" and "Cancel" buttons for explicit control over saving changes.
- The hour arc has been re-enabled in the clock visualization for longer timer sessions.
- The maximum duration for any timer phase is now capped at 24 hours (1440 minutes).

feat: Final UX improvements for Pomodoro timer

---

index.html
js/tools.js

This commit addresses a regression where the continuous mode functionality was removed. It also adds a user-requested visual feedback feature for the snooze function.
- Adds a 'Continuous Mode' toggle to the Pomodoro settings.
- When enabled, the timer automatically proceeds to the next cycle.
- When disabled, the new interactive alarm controls are shown.
- The timer display now turns mustard yellow when the timer is snoozed to provide clear visual feedback.
- The timer color is reset when the snooze ends or the timer is reset.

fix: Re-implement continuous mode and add snooze color change

---

index.html
js/clock.js
js/main.js
js/tools.js

This commit refactors the Pomodoro timer settings UI and fixes a bug in the continuous mode functionality, addressing user feedback.
- Removes the static, on-page settings panel from the Pomodoro tab to reduce clutter and eliminate non-functional duplicate inputs.
- Adds a 'Custom' button to the Pomodoro controls that opens a new modal for all timer settings.
- The new modal contains inputs for work, short break, and long break durations, as well as the 'Continuous Mode' toggle.
- Refactors the JavaScript to manage Pomodoro settings in the state object, removing the dependency on static DOM elements.
- Fixes a bug in continuous mode where the next cycle would be prepared but not automatically started. The timer now begins counting down immediately.

fix: Replace static settings with modal and fix continuous mode

---

js/clock.js

This commit resolves a series of UI and logic issues with the Pomodoro timer, culminating in a full refactor of its settings management and a fix for a critical rendering bug.
- Replaces the static, on-page settings panel with a 'Custom' button that opens a new modal for all timer settings (`pomodoroSettingsModal`).
- The new modal contains inputs for work, short break, and long break durations, as well as the 'Continuous Mode' toggle.
- Refactors the JavaScript in `js/tools.js` to manage Pomodoro settings in a central state object, removing dependencies on static DOM elements.
- Fixes a bug in continuous mode where the next cycle would not start automatically.
- Fixes a critical bug in `js/clock.js` where the `drawPomodoro` function was attempting to read from deleted DOM elements, …

fix: Refactor Pomodoro to use state and add settings modal

---

index.html
js/tools.js

This commit replaces the single Pomodoro timer display with a more informative "at-a-glance" dashboard, as requested by the user.
- The `pomodoroPanel` in `index.html` now contains a vertical stack of three displays for Work, Short Break, and Long Break durations.
- The 'Oswald' font is imported and applied to the new timer displays for a distinct visual style.
- New CSS classes have been added to style the dashboard and handle dynamic coloring.
- The display logic in `js/tools.js` has been refactored into a new `updatePomodoroDashboard` function.
- This function updates all three timer displays, formats the time to HH:MM:SS, and applies colors based on the timer's state (green for active, red for paused, white for inactive).

feat: Implement Pomodoro timer dashboard view

---

index.html
js/tools.js

This commit adds mute and snooze functionality to the regular timer, mirroring the features of the Pomodoro timer.
Key changes include:
- Extending the timer state to include `alarmPlaying`, `isMutedThisCycle`, and `isSnoozing`.
- Adding new UI controls for mute, snooze, and stop that appear when the timer finishes.
- Refactoring the `timerFinished` function to handle the end-of-cycle state, allowing for user interaction instead of automatic reset (unless in interval mode).
- Implementing `muteTimerAudio`, `snoozeTimer`, and `stopTimerAlarm` functions to manage the new interactions.
- Updating `resetTimer` to clear all new state flags and stop any playing audio.
- Adding visual feedback for the snoozing state by applying a `.snoozed` class to the timer inputs.

feat(timer): Add mute and snooze functionality to timer

---

index.html

Implements a new layout for the desktop view where the UI panel (Settings, Tools, About) appears as a semi-transparent overlay on the right side of the screen, rather than pushing the main clock canvas to the side.
- The canvas container now remains centered and full-width when a UI panel is active.
- The UI container is styled with a semi-transparent background and a backdrop-filter for a blurred glass effect.
- The changes are scoped to desktop screens (min-width: 769px) and do not affect the existing mobile layout.
- All changes are contained within index.html as requested.

Feat: Implement UI Overlay for Desktop View

---

index.html

Refactored the CSS to prevent the UI panel from affecting the main content layout on desktop screens.
- Changed `body` `justify-content` to `center` to ensure the clock container is always centered.
- Made `.ui-container` `position: absolute` within a desktop media query to remove it from the document flow.
- Implemented a CSS transform to slide the panel in and out, controlled by the existing `body.panel-open` class.
This change ensures the clock remains perfectly centered, regardless of the UI panel's visibility, and makes the panel a true overlay as intended. The mobile layout remains unaffected.

fix(css): Make UI panel a true overlay on desktop

---

index.html

This commit refactors the HTML structure by removing the unnecessary .ui-container div. The child view panels (#toolsView, #settingsView, #aboutView) are now direct children of the body.
The CSS has been updated to apply overlay and layout styles directly to a new .view-panel class on these views. The JavaScript was reviewed and confirmed to be unaffected as it uses ID-based selectors.
This change simplifies the DOM structure and layout logic while preserving all functionality and visual appearance on both desktop and mobile.

Refactor: Remove .ui-container and simplify layout

---

index.html

This commit adjusts the CSS for the #mainView element to move the main navigation buttons higher up on the screen. The vertical alignment is changed from `center` to `flex-start` and a `padding-top` is added.
This change addresses the user's feedback to move the unopened toolbar to the top right of the screen.

Style: Adjust vertical position of main navigation toolbar

---

index.html
js/ui.js

This commit addresses two main issues with the user interface: a non-responsive layout on mobile devices and a disjointed timer functionality.
- Implementing CSS media queries to ensure the layout is fully responsive on screens narrower than 768px. On mobile, the clock is now positioned at the top, with the UI panels below it.
- Consolidating the Timer, Pomodoro, and Stopwatch tools into a single tabbed interface within the "Tools" panel for a more unified user experience.
- Refactoring the JavaScript UI logic to use CSS classes for showing and hiding panels, improving code quality and maintainability.
- Removing the "Default" tab from the tools view and setting the "Timer" as the default active tool.

feat: Implement responsive UI and consolidate timer

---

index.html

This commit resolves a follow-up issue where buttons in the UI panels were inoperable on mobile devices.
The root cause was the `.clock-square-wrapper` element overflowing its parent container in the mobile view, invisibly covering the UI panels and intercepting click events.
The fix adds `max-height: 100%` to the `.clock-square-wrapper` CSS rule, ensuring it is always constrained within its parent's bounds. This resolves the element overflow and makes the buttons fully interactive again.

fix: Prevent clock overflow and repair mobile buttons

---

index.html
js/ui.js

Re-introduces the 'Default' tab in the tools section, allowing the user to set the main clock as the focus while keeping the tools panel open.
- Added a 'Default' button to the tool tabs in `index.html`.
- Updated `js/ui.js` to handle the new tab:
- Added the 'Default' tab to the `toolTabs` object.
- Created an event listener that sets the application mode to 'clock' when the 'Default' tab is clicked.
This restores the previously existing functionality as requested by the user.

feat: Reactivate 'Default' clock option in tools

---

index.html
js/ui.js

This commit introduces two safeguards to the suggestion box feature to prevent abuse:
- Empty messages are no longer allowed. The message body must contain at least one character.
- Users are limited to 3 submissions per device per 24-hour period. This is tracked using localStorage.
Additionally, a message "Limited to 3 per day." is now displayed in the feedback form section to inform users of the submission limit.

Add safeguards to suggestion box

---

index.html

The circles on the canvas and the digital time display were being obscured by the UI panels, which had a higher z-index.
This change ensures the clock's canvas and the digital display are always the topmost elements by:
- Adding `position: relative` and `z-index: 102` to the `canvas` element's style.
- Adding `z-index: 102` to the `#digitalDisplay` element's style.
This places them above the UI panels, which have a maximum z-index of 101.

feat: Make clock and digital display the topmost layer

---

index.html
js/tools.js

This commit introduces a new "Style" toggle to the timer settings panel, located directly below the "Repeat" toggle.
The new toggle is wired into the application's state management in `js/tools.js`. A new `style` property has been added to the `state.timer` object, which is updated when the toggle is clicked. The state of the toggle is persisted to `localStorage` and correctly restored on page load.
The default state for the new toggle is "on" (checked), as per the requirements.

feat: Add style toggle to timer settings

---

js/clock.js

This commit introduces the logic for a new timer display style, "Absolute Position," which is activated when the "Style" toggle is in the OFF position.
The key changes are in `js/clock.js` within the `drawTimer` function:
- When the timer style is OFF, the progress of each arc (days, hours, minutes, seconds) is now calculated based on its value relative to a standard clock face (e.g., `minutes / 60`).
- Implements the "full arc" behavior: if a time unit is 0 but a larger unit has a non-zero value (e.g., for a timer of 1 hour, 0 minutes), the arc for the smaller unit will be drawn as a full circle.
The default timer style (Style ON) remains unchanged.

feat: Implement absolute position style for timer

---

js/tools.js

This commit addresses user feedback on the timer style feature.
Key changes:
- Sets the default timer style to "absolute position" (Style OFF) by changing the default value of `state.timer.style` to `false`.
- Implements a live preview for the timer. The timer arcs now update immediately when the user changes the timer inputs (on blur) or toggles the style switch. This is achieved by dispatching a `statechange` event from the relevant event listeners in `js/tools.js`.
- The "absolute position" logic in `js/clock.js` correctly calculates arc progress based on the value's position on a clock face (e.g., 15 minutes is 25% of the circle).

fix: Correct timer style logic and implement live preview

---

index.html
js/settings.js

- Replaces the color palette buttons with a dropdown menu.
- Updates the color themes with the new hexadecimal codes provided by the user.
- Fixes the layout of the "Visuals & Colors" section.
- Removes the "Gradient" feature and simplifies the color logic.

feat: Implement color palettes dropdown and new color themes

---

js/clock.js

- Adds a "shine" effect to the "Candy" theme using a linear gradient.
- Adds a "glow" effect to the "Neon" theme using a shadow.
- Updates the `drawArc` function to handle these special effects.

feat: Add special effects to color themes

---

index.html
js/ui.js

This change addresses the user's request to have the "Clock Only" option as the default tool when the application is first opened.
- The "Clock Only" button has been moved to the top of the tool selection menu in `index.html`.
- The `js/ui.js` file has been updated to dispatch a `modechange` event, setting the mode to 'clock' on initial load if no saved state is present in localStorage.

feat: Make "Clock Only" the default tool and move to top of list

---

js/clock.js

The wipe animation that occurs when an arc completes a full cycle was visually jarring in "inverse mode".
This change modifies the drawing logic to detect if inverse mode is active. If it is, the wipe animation is skipped, providing a smoother visual experience as requested.

fix(clock): Disable wipe animation in inverse mode

---

index.html
js/ui.js

This moves the "Alarms" button from the main navigation bar to within the "Tools" menu, as part of a larger UI refactoring effort.
The following changes were made:
- In `index.html`, the "Alarms" button was moved from the `main-nav-buttons` div to the `tool-select-menu` div.
- The button's class was changed from `main-nav-button` to `tool-select-button` and its text was set to "Alarms".
- In `js/ui.js`, the old event listener for the "Alarms" button was removed.
- A new event listener was added to the `tool-select-button`s to handle the "Alarms" button's click event and navigate to `alarms.html`.

Refactor: Move Alarms button to Tools menu

---

index.html

This commit fixes an issue where the buttons in the new bottom toolbar were not clickable due to a z-index conflict with the clock canvas. It also refines the toolbar's appearance and disappearance animation as per user feedback.
The following changes were made:
- In `index.html`, the `z-index` of the `bottom-ui-container` was increased to ensure it is rendered on top of the canvas.
- The CSS for the `#bottom-toolbar` was updated to create an animation where it scales and moves from the center of the clock to its final position at the bottom.

Fix: Make toolbar buttons clickable and refine animation

---

index.html

This change restores the functionality of the options button, which was inadvertently broken in the previous commit.
The `main-nav-button` class has been re-added to the button, and the custom styling class has been simplified to only override the necessary properties. This ensures that any implicit dependencies on the original class are maintained.

fix: Restore options button functionality

---

index.html

This commit centers the clock on the screen by removing the right padding from the canvas container. This was previously used to make space for the controls panel on desktop view.
The 'Options' button has been moved from the digital display to the main body of the page and is now positioned in the absolute center of the screen, on top of the clock.

feat: Center clock and options button

---

js/main.js
js/ui.js

Previously, the UI component would read the application state from localStorage independently, causing a race condition where the timer panel could be visible on startup even when the application was in 'clock' mode.
This commit refactors the initialization logic to ensure a single source of truth for the application state. `js/main.js` now passes the correctly initialized state to `js/ui.js`, which uses it to set the initial visibility of the UI panels. This prevents the timer panel from being displayed incorrectly on application load.

Refactor initialization to hide tool panels on startup.

---

js/clock.js

The default timer style used integer-based calculations for arc progress, causing the timer hands to jump between units rather than animating smoothly.
This change updates the progress calculation logic in `js/clock.js` for the default timer style. It now uses the floating-point value of the remaining time with the modulo operator to determine the arc's position. This results in a smooth, continuous sweeping animation for the hours, minutes, and seconds arcs, consistent with the app's other animation styles.

feat: Animate default timer style smoothly

---

index.html

Replaces the Phosphor icon font library with a new set of SVG icons from the `assets/icons/` directory.
- The `index.html` file has been updated to use `<img>` tags with the new SVG icons.
- A new CSS class, `.svg-icon`, has been added to style the new icons, ensuring they are sized correctly and visible on a dark background.
- The script for the old Phosphor icon library has been removed.
- The `alarms.html` and `time-calc.html` files were left untouched as per the user's request and because they either were excluded or did not contain icons.

feat: Replace Phosphor icons with new SVG icons

---

index.html

This commit adds an attribution and version number to the bottom-left corner of the screen.
The text "PolarClockPro || v1.0 || by Salamanca-Tech" is displayed using the "Oswald" font, with white color and 33% opacity.
The attribution is hidden on small screens to maintain a clean user interface on mobile devices.

Feat: Add attribution and version number

---

js/clock.js

This commit fixes a visual bug where the 'Week of the Year' and 'Day' arcs on the main clock face could appear misaligned or not update correctly.
The cause was a non-standard implementation for calculating the week of the year and the total number of weeks in a year. This has been replaced with a robust implementation that follows the ISO 8601 standard. This ensures the week-based arcs are always accurate and aligned with standard calendars.

fix(clock): Use ISO 8601 for week calculations

---

js/settings.js
js/tools.js

This commit addresses two issues:
1.  It fixes a bug where end-of-cycle audio for timers and Pomodoro cycles would fail to play. This was caused by referencing a non-existent `timerSound` setting. The code has been corrected to use the appropriate `alarmSound` setting for these alerts, which was then changed to a new, less jarring `timerSound` setting per user feedback.
2.  It finalizes the relocation of the Pomodoro settings into the main tool panel, ensuring the UI is clean and the new live-updating inputs are fully functional.
Changes include:
- Adding a new `timerSound` setting in `js/settings.js` with a more subtle default.
- Updating `js/tools.js` to use `settings.timerSound` for all timer and Pomodoro alerts, decoupling it from the main alarm sound.
- Verifying the relocation of …

Fix: Correct timer audio and finalize settings relocation

---

js/tools.js

This commit ensures that the Pomodoro timer's mute state is reset at the beginning of each new cycle. If a user mutes the audio during one cycle, the mute will be automatically disabled for the next cycle, allowing the end-of-cycle alert to play.
This is achieved by updating the `startNextPomodoroPhase` and `resetPomodoro` functions in `js/tools.js` to set `state.pomodoro.isMuted` to `false` and to remove the 'active' class from the mute button's UI.

Fix: Reset Pomodoro mute state at the start of each new cycle

---

js/clock.js

This commit adjusts the rendering order of the clock arcs to make the new alarm countdown arc the absolute outermost ring, as requested in follow-up feedback.

fix: Adjust alarm arc to be the outermost ring

---

index.html
js/time-calculator.js
js/tools.js

This commit addresses several user experience issues with the timer feature.
- The four separate input fields for days, hours, minutes, and seconds have been replaced with a single, more intuitive text input that accepts natural language time expressions (e.g., "1h 30m", "90 minutes").
- The timer's alarm controls (mute, snooze) are now hidden until the alarm is actively sounding, providing a cleaner initial UI.
- A bug that allowed the "Test" sound button to be clicked multiple times, causing sounds to stack, has been fixed. Now, only one test sound can play at a time.
- The superfluous "Mute" button in the timer sound settings has been removed.
To support the new input, `js/time-calculator.js` was refactored to expose its parsing functions through a global `TimeCalculator` object for …

Refactor: Improve Timer UX and Fix Sound Issues

---

index.html
js/tools.js

This commit applies the same UX improvements to the stopwatch that were previously applied to the timer.
- A bug that allowed the "Test" sound button to be clicked multiple times, causing sounds to stack, has been fixed. Now, only one test sound can play at a time.
- The superfluous "Mute" button in the stopwatch sound settings has been removed.

Refactor: Improve Stopwatch UX and Fix Sound Issues

---

index.html
js/tools.js

This commit introduces a new feature to the stopwatch that allows users to play a sound at a specified interval.
- A new "Interval Sound" section has been added to the stopwatch panel in `index.html`.
- This section includes a toggle switch to enable or disable the feature and HH:MM:SS inputs to set the interval duration.
- The `js/tools.js` file has been updated to include the necessary state management and logic to track the stopwatch's elapsed time and play the selected sound at the specified intervals.

Feat: Add Interval Sound to Stopwatch

---

index.html

This commit moves the lap times list to the bottom of the stopwatch panel, as requested by the user. This improves the layout by grouping all the controls and settings together at the top, with the lap times displayed below.

Fix: Move Stopwatch Lap Times to Bottom

---

index.html

This commit introduces a new CSS media query to make the application's layout responsive for mobile devices with a screen width of 600px or less.
- A new `#mobile-nav-bar` container that wraps the main navigation buttons.
- A new `@media (max-width: 600px)` query in the main stylesheet (`index.html`).
- Styles to make `#mobile-nav-bar` a fixed flex container at the bottom of the screen.
- Adjustments to the main clock container (`.canvas-container`) to prevent overlap with the new navigation bar.
- The navigation icons' position is set to `relative` within the media query as requested.
Note: The user's request mentioned `#clock-container`, but the actual element in the codebase is `.canvas-container`. The change was applied to the correct element.

feat: Make layout responsive for mobile devices

---

index.html

This commit increases the padding of the navigation icons in the mobile view to make them easier to use on a touchscreen. The padding is increased to 15px for screens with a width of 600px or less.

feat: Increase tappable area of mobile navigation icons
