- index.html
This commit introduces a significant refactoring of the user interface and the JavaScript codebase to improve user experience and maintainability.
UI Consolidation and Modernization:
- The "Customize" and "Settings" pages have been merged into a single, intuitive "Settings" panel, simplifying navigation.
- The text-based navigation buttons have been replaced with modern, circular icon-based buttons using Phosphor Icons for a cleaner and more intuitive aesthetic.
Code Refactoring for Health and Maintainability:
- The JavaScript code has been refactored into multiple logical, self-contained modules using the Immediately Invoked Function Expression (IIFE) pattern.
- A single global `App` object is used as a namespace to prevent pollution of the global scope.
- All JavaScript initialization …
> Refactor: Modernize UI and Modularize JavaScript

- index.html
Reverts SALAMANCA-TECH/PolarClockPro#69
> Revert "feat: Implement Pomodoro timer display on canvas"

- index.html
- js/main.js
- js/settings.js
This commit removes the "Glow" and "Pulse" visual effects from the application.
- Removed the "Enable Glow Effect" and "Enable Pulse Effect" toggles from the settings panel in index.html.
- Removed the corresponding JavaScript logic in js/settings.js and js/main.js that handled saving, loading, and applying these settings.
- Removed the CSS keyframes and classes related to the "glow" and "pulse" animations from index.html.
> Remove Glow and Pulse Effects

- js/tools.js
This commit integrates state management for the mute and snooze features in the Pomodoro timer and provides visual feedback to the user.
Key changes include:
- Ensuring that the end-of-cycle sound does not play if the timer is muted for the current cycle.
- Resetting temporary state flags (isSnoozing, isMutedThisCycle, lastMinuteSoundPlayed, currentAudio) when a new cycle begins or the timer is reset.
- Stopping any playing audio when the timer is reset.
- Updating the status display to show "Snoozing" when the timer is in a snoozed state.
- Applying a .snoozed CSS class to the timer display for visual feedback during snoozing.
- Refactored inconsistent isSnoozed property to isSnoozing for clarity and correctness.
> feat(pomodoro): Integrate state management and user feedback

- js/clock.js
The Custom Timer animation has been updated to provide a counter-clockwise emptying effect, consistent with the application's established aesthetic.
The rendering logic in `js/clock.js` was modified to change the calculation of the arc's start and end angles. The timer now starts as a full circle and shrinks back towards the 12 o'clock position as time elapses.
> Refactor: Update Custom Timer animation to match Pomodoro style

- js/clock.js
Based on user feedback, the Custom Timer animation has been updated to provide a counter-clockwise emptying effect.
The rendering logic in `js/clock.js` was modified to have the timer arc's head move counter-clockwise as time elapses, starting from a full circle and shrinking towards the 12 o'clock position.
> Refactor: Update Custom Timer animation to be counter-clockwise

- index.html
- js/clock.js
- js/tools.js
This commit implements the final set of features and fixes for the timer functionality based on user feedback.
Key changes:
- **Dynamic Arc Visibility:** The timer now displays arcs for months and days when the timer duration is sufficiently long. This includes a new "Months" input field.
- **Separator Logic:** The timer's arc separators now fully respect the global settings for both "standard" and "ruler" modes.
- **12/24 Hour Mode:** The timer's hour arc now correctly displays in either 12-hour or 24-hour format based on the global setting.
- **Smooth Animation:** The timer arcs now animate smoothly during countdown. This was achieved by refactoring the drawing logic to use precise floating-point time values when the timer is running, while preserving the static "full arc" preview when …
> feat: Finalize timer styles and add requested features

- index.html
- js/clock.js
- js/tools.js
Reverts SALAMANCA-TECH/PolarClockPro#188
> Revert "feat: Finalize timer styles and add requested features"

- index.html
This commit introduces the 'Meditative Mode' to the application, a new tool for guided breathing exercises.
The feature includes:
- A new 'Meditative' option in the tool selection menu.
- A dedicated control panel for the mode with a 'Start/Stop' button and a pattern selector.
- Two breathing patterns: '4-7-8' and '7-11'.
- Custom arc animations and colors that correspond to the selected breathing pattern (inhale, hold, exhale).
- The animation sequence runs in a continuous loop until stopped.
- When stopped or when switching away from the mode, the arcs reset to their full state.
All logic for this feature has been added directly to `index.html` as per the requirements.
> feat: Add Meditative Mode feature

- index.html
This commit adjusts the visual appearance of the Meditative Mode arcs based on user feedback.
Changes:
- The overall diameter of the arc group has been reduced for a more compact appearance.
- The thickness of the arcs has been increased to make them more prominent.
The timing and animation logic remains the same, ensuring each step of the breathing exercise abides by its specified duration.
> refactor: Adjust Meditative Mode arc appearance

- index.html
- js/ui.js
Reverts SALAMANCA-TECH/PolarClockPro#208
> Revert "Style: Update digital display layout"

- index.html
Reverts SALAMANCA-TECH/PolarClockPro#207
> Revert "Refactor: Relocate digital display and fix layout issues"

- index.html
Reverts SALAMANCA-TECH/PolarClockPro#213
> Revert "fix: Restore options button functionality"

- js/clock.js
- js/tools.js
This commit enhances the user interaction with the timer in the 'Default' style mode.
1.  Real-time arc drawing: The timer arcs now update instantly as the user types values into the days, hours, minutes, and seconds input fields. This is achieved by changing the event listeners on these inputs from 'blur' to 'input'.
2.  Input-based arc length: When the timer is not running, the length of each arc directly corresponds to the numerical value entered in its respective field (e.g., an input of '30' in the minutes field will render the arc at 50% of the circle).
3.  Initial state: The timer now appears at 0% when the inputs are at 0, which is the default state.
The existing countdown animation for a running timer remains unchanged. These modifications only affect the …
> feat(timer): Update timer interaction and drawing logic

- js/clock.js
This commit introduces a new animation for the clock's 'Inverse Mode'.
Key changes:
- When any time arc is one second away from completing its cycle, a secondary 'anticipation' arc is now drawn.
- This anticipation arc completes a full circle in one second, visually indicating the upcoming cycle completion.
- The primary arc continues its smooth, continuous countdown as before.
- To support this feature, all time arc calculations in `drawClock` have been refactored to be fully continuous and based on millisecond precision, improving the overall smoothness of the clock animation.
> feat: Implement 'Two Arc' animation for Inverse Mode

- js/clock.js
- js/settings.js
Replaces the "Flow" toggle with a dropdown menu, allowing users to select various time intervals for the automatic theme-changing feature.
This change also introduces:
- Synchronized timing: Theme changes now occur at precise intervals (e.g., on the hour, every 5 minutes at :05, :10), with "BSG" as a special case.
- Clockwise wipe transition: A smooth, animated transition between themes.
- Modified index.html to replace the checkbox with a select element.
- Updated settings.js to dispatch a custom event on theme change.
- Refactored clock.js to handle the new timing logic and implement the transition animation.
> feat: Implement advanced flow controls and transition

- assets/content/about.txt
- assets/content/how-to-use.txt
- assets/content/pomodoro.txt
This commit completely rewrites the user-facing documentation files (`about.txt`, `how-to-use.txt`, and `pomodoro.txt`) to be comprehensive, accurate, and up-to-date with the application's current features.
- `about.txt` now clearly explains what a polar clock is and how to read it.
- `how-to-use.txt` has been overhauled into a complete user guide, detailing all display settings, clock tools (Timer, Stopwatch, Pomodoro), and sound settings.
- `pomodoro.txt` has been enhanced with details about advanced features like custom durations, continuous mode, and alarm controls.
The new documentation provides a much-improved resource for users to understand and utilize all the features of Polar Clock Pro.
> Docs: Rewrite and update user documentation

- js/clock.js
This commit delivers a major enhancement to the Timer mode based on user feedback.
1.  **Expanded Time Units:** The timer now supports rendering arcs for years, months, and weeks, in addition to the existing units. This allows the clock to accurately represent very long durations (e.g., 365 days). The `month` arc is repurposed, and a new `year` arc has been added to the drawing system specifically for the timer.
2.  **Fluid Animation:** The timer animation is now perfectly smooth. The drawing logic for all arcs now uses floating-point time values, eliminating the "jerky" second-by-second movement of the previous implementation.
These changes build upon the previous addition of ruler-mode support, making the timer a more robust and visually appealing feature.
> feat(timer): Add year/month arcs and smooth animation

- js/clock.js
- js/main.js
This commit introduces a persistent alarm system and a visual indicator for tracked alarms on the main clock face.
Key changes:
- Alarms are now checked globally in `js/main.js`, allowing them to ring even when the alarms page is not active.
- A robust timing mechanism using a `lastChecked` timestamp ensures alarms are not missed if the tab is backgrounded.
- A single alarm can be 'tracked' via the UI on the alarms page.
- When an alarm is tracked, a thin, red, outer arc is drawn on the main clock, visually counting down to the next alarm occurrence.
- The countdown arc's duration is accurately calculated based on the alarm's repeat schedule (e.g., 24 hours for a daily alarm, 7 days for a weekly one).
- Logic for one-time alarms has been improved to ensure they fire correctly.
> feat: Implement persistent alarms and visual countdown arc

- index.html
Reverts SalamancaTech/PolarClockPro#278
> Revert "feat: Make layout responsive for mobile devices"
